spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.100:9432/czkj
    username: postgres
    password: postgres
#   datasource:
#     driver-class-name: oracle.jdbc.OracleDriver
#     url: jdbc:oracle:thin:@192.168.0.100:9521:xe
#     username: tdmap
#     password: tdmap
#dao日志打印
logging:
  level:
    com.cmsiw: trace
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.cmsiw.sys.entity
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
com:
  cmsiw:
    mobile:
      enabled: true